import os

SPACEMASTER_GRAPHQL = os.getenv(
    "SPACEMASTER_GRAPHQL",
    "https://07098df7d936.ngrok-free.app/graphql"
)

EVENT_STATUS_SCHEDULED = "SCHEDULED"
EVENT_STATUS_ONGOING = "ONGOING"
EVENT_STATUS_COMPLETED = "COMPLETED"
EVENT_STATUS_CANCELLED = "CANCELLED"

VALID_EVENT_STATUSES = [
    EVENT_STATUS_SCHEDULED,
    EVENT_STATUS_ONGOING,
    EVENT_STATUS_COMPLETED,
    EVENT_STATUS_CANCELLED
]

BOOKABLE_EVENT_STATUSES = [
    EVENT_STATUS_SCHEDULED
]

REQUIRED_SPACEMASTER_FIELDS = [
    "venue_id",
    "room_id",
    "start_time",
    "end_time"
]
