import os

# SpaceMaster URL (Updated)
SPACEMASTER_GRAPHQL = os.getenv(
    "SPACEMASTER_GRAPHQL",
    "https://7318c00bb235.ngrok-free.app/graphql"
)

EVENT_STATUS_SCHEDULED = "SCHEDULED"
EVENT_STATUS_ONGOING = "ONGOING"
EVENT_STATUS_COMPLETED = "COMPLETED"
EVENT_STATUS_CANCELLED = "CANCELLED"

VALID_EVENT_STATUSES = [
    EVENT_STATUS_SCHEDULED,
    EVENT_STATUS_ONGOING,
    EVENT_STATUS_COMPLETED,
    EVENT_STATUS_CANCELLED
]
